---
- name: Check local workstation can run ansible cloud commands on Azure
  hosts: localhost-ansible
  tags: azure
  tasks:

    - name: Test credentials- List all resources groups
      azure_rm_resourcegroup_facts:
        tags:
        - Testing
    
    - name: Test credentials - Create a resource group
      azure_rm_resourcegroup:
        name: Testing
        location: westus
        
    - name: Test credentials- List all resources groups
      azure_rm_resourcegroup_facts:
        tags:
        - Testing

    - name: Test credentials - Delete a resource group
      azure_rm_resourcegroup:
        name: Testing
        location: westus
        state: absent
